### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by camjac251** [RandomUser99/TwitchVods#1]
I've tried using .NET core as well as the full visual studio 2017 and both give the same result. A dll with other files is generated so I try runnning the dll directly and get this error

```cmd
C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\bin\Debug\netcoreapp2.0>dotnet TwitchVods.Core.dll
TwitchTool, starting

Unhandled Exception: System.AggregateException: One or more errors occurred. (String was not recognized as a valid DateTime.) ---> System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at CallSite.Target(Closure , CallSite , Type , Object , String , CultureInfo )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at TwitchVods.Core.Models.Video.FromJson(Object data) in C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\Models\Video.cs:line 89
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at TwitchVods.Core.Twitch.VideoFetcher.<GetVideos>d__2.MoveNext() in C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\Twitch\VideoFetcher.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TwitchVods.Core.Worker.<GetVideos>d__5.MoveNext() in C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\Worker.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchVods.Core.Worker.<WriteChannelVideos>d__4.MoveNext() in C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\Worker.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchVods.Core.Program.<MainAsync>d__1.MoveNext() in C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\Program.cs:line 31
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchVods.Core.Program.Main(String[] args) in C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\Program.cs:line 16

C:\Users\User\Desktop\TwitchVods-master\TwitchVods.Core\bin\Debug\netcoreapp2.0>

```

**Comment by RandomUser99** [comment]
This commit should hopefully fix the issue:

https://github.com/RandomUser99/TwitchVods/commit/7ad42e9be59c2d00284005fa777b846b3d81ddb7

Can you pull the latest version and retry please?

**Comment by camjac251** [comment]
That seems to have fixed it. It is running properly now. Would it be possible to request a channel for the tvods website? I am using it locally now since the channel wasn't on the site but could Shroud be added to the site for browsing? All vods are archived there it seems, none deleted (like Lirik) so it'd be nice to browse and see when game changes happen.

**Comment by RandomUser99** [comment]
Yeah sure. Send the channel name over and I'll add it in to the tvods site.

**Comment by camjac251** [comment]
The channel name is Shroud

**Comment by camjac251** [comment]
I was thinking of a feature request although it may seem like a lot of work. Your code is very useful for browsing through VODs and finding exactly what you want although it is limited to the channels you have setup. Would it be possible to offer an add function on the main homepage where a user can type in a username and complete a Captcha (to prevent spam) and it will add the user's generated VOD page to the list?. Then for it to auto update, it will update the same way your current ones do if it is accessed at least once in 15 days. That could prevent twitch temp banning the IP for overuse of the API. If it is accessed outside of the 15 days then it could update right then before displaying possibly? Seems complicated as I explain it.

**Comment by RandomUser99** [comment]
It is possible, but at the moment the amount of effort just isn't worth it. Its much easier for me just to add the channel to the channels.txt file right now.

**Comment by RandomUser99** [comment]
I've added it in. You can access it at https://tvods.se/v/shroud.html
